# Generated by Django 2.2.6 on 2019-11-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasajero',
            options={'ordering': ['primer_apellido', 'primer_nombre', 'nacionalidad', 'correo_electronico']},
        ),
        migrations.RenameField(
            model_name='pasajero',
            old_name='segundo_nombre',
            new_name='primer_apellido',
        ),
    ]
